### ISSUE TITLE
Can't download ad card

### ISSUE THREAD

**Issue by Hirizon** [3003h/FEhViewer#224]
v1.3.6+496 when I update this version, the download function on SD card failed and gave such error. Miui 13 android 12

**Comment by Hirizon** [comment]
![Screenshot_2023-01-05-22-37-13-768-edit_com honjow fehviewer](https://user-images.githubusercontent.com/122037706/210820782-543490a7-474a-4179-b608-4164df138560.jpg)

**Comment by Hirizon** [comment]
![Screenshot_2023-01-05-22-35-33-430-edit_com honjow fehviewer](https://user-images.githubusercontent.com/122037706/210820869-5adaf7e7-c04a-4e98-bd13-03354ce5ca4c.jpg)

**Comment by honjow** [comment]
Try reselecting the download path first. If you don't mind, let me see what the path looks like after reselecting it. I was not able to test this scenario because my development and testing device does not support SD cards.

**Comment by Hirizon** [comment]
![Screenshot_2023-01-08-22-46-45-304_com honjow fehviewer](https://user-images.githubusercontent.com/122037706/211206010-596e8f57-1bad-48d5-8674-9e2fdd77c723.jpg)
this is my link in the app i made

**Comment by Hirizon** [comment]
![Screenshot_2023-01-08-22-50-18-828_com mi android globalFileexplorer](https://user-images.githubusercontent.com/122037706/211206161-dad1d4a9-9533-4e12-91ea-cd55487a0108.jpg)
and it has another error that creates a lot of folders of stories to download
