### ISSUE TITLE
画廊名称显示问题

### ISSUE THREAD

**Issue by zhanbao2000** [3003h/FEhViewer#228]
## 版本

 - Android v1.3.8+498
 - iOS v1.3.8+498

## 描述

同一个画廊，在App内第一次和第二次打开时，显示的画廊名称不一致。

第一次打开时，画廊名称显示为日文标题，顶部小字显示为英文标题

第二次（及以后）打开时，画廊名称显示为英文标题，顶部小字显示为日文标题

## 复现步骤

1. 找一个从没在App内打开过的画廊，然后打开，等待UI加载完成后，可以看到画廊名称显示为日文标题，顶部小字显示为英文标题

![图片](https://user-images.githubusercontent.com/29254102/211740992-2fb26bce-1269-4f4d-bd9d-1ffd9a7f97cf.png)

2. 退回到画廊列表，并再次进入这个画廊，等UI加载完成后，可以看到画廊名称显示为英文标题，顶部小字显示为日文标题

![图片](https://user-images.githubusercontent.com/29254102/211741033-8ec0b3c2-19f2-4600-9e72-9bf3eeae84f1.png)

3. 之后每次进入该画廊，显示效果均与2中相同

## 期望的修复

根据配置文件来决定

如果优先以日文作为标题，则将画廊名称显示为日文标题，顶部小字显示为英文标题。否则反过来

## 备注

复现的时候，我的配置文件中的 `图库的名字显示` 设置为 `日文标题`。

如果将其变更为 `默认标题`（即英文标题） 则复现时不会发生1中的情况

**Comment by honjow** [comment]
@zhanbao2000 已知问题，待后续修正
