### ISSUE TITLE
瀑布流-大显示与webdav同步阅读进度问题

### ISSUE THREAD

**Issue by ArtMoe** [3003h/FEhViewer#288]
1. 瀑布流-大样式下，刷新会闪一下白屏。
2. webdav同步阅读进度切换设备后无法同步进度，比如设备1阅读到10页，设备2同步后继续从10页往后读，刷新后又会变回第10页。

**Comment by A9037102** [comment]
+1

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Moe ***@***.***>
Sent: Thursday, November 2, 2023 10:50:33 AM
To: 3003h/FEhViewer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [3003h/FEhViewer] 瀑布流-大显示与webdav同步阅读进度问题 (Issue #288)


  1.  瀑布流-大样式下，刷新会闪一下白屏。
  2.  webdav同步阅读进度切换设备后无法同步进度，比如设备1阅读到10页，设备2同步后继续从10页往后读，刷新后又会变回第10页。

―

**Comment by 3003h** [comment]
应该都解决了

**Comment by A9037102** [comment]
此文件不具有多于意义仅为了在定时发送
