### ISSUE TITLE
关于阅读配额的消耗和网页端不一致

### ISSUE THREAD

**Issue by MegoCat** [3003h/FEhViewer#290]
首先在My Settings页面设置Image Size Settings为2400x，打开Overview页备用

网页端：进入大图阅读页，等待首张图片加载，观察得Overview页Image Limits扣除5。点击图片翻页，观察得此后每翻一页Image Limits仅扣除1。

安卓手机端：任意选择Gallery进入，点击阅读，等待自动加载完成，观察Overview页Image Limits值。
向后翻1页，观察得Image Limits扣除5。再向后翻1页，观察Image Limits仍扣除5

希望咱们软件也能实现翻页低配额消耗，和网页端保持一致

测试版本1.4.8(518)，pixelOS android13

**Comment by 3003h** [comment]
经测试，可以复现
原因我基本也弄清楚了，需要改下加载的请求方式
另外好像只有2400这样的高分辨率才会这样，因为一直用着默认的，好像都是1点

**Comment by 3003h** [comment]
> > 经测试，可以复现 原因我基本也弄清楚了，需要改下加载的请求方式 另外好像只有2400这样的高分辨率才会这样
> > 经过讨论，怀疑是eh现在有bug。因为测试会有不扣的情况
> 
> 不扣是否是因为eh每分钟自动回复1点呢？刷新的一瞬间正好自动回复了。有时可测得扣除4点也是这个原因

不是。是真的没扣。。连续看多张。或者mpv模式看完都没扣

**Comment by 3003h** [comment]
新版已经做了。看看。
