### ISSUE TITLE
画廊站点设置为exhentai时，重定向缩略图链接仍然请求s.exhentai.org

### ISSUE THREAD

**Issue by ameyukisora** [3003h/FEhViewer#293]
目前在windows和Android客户端上都可以观察到，这导致缩略图有时加载超时。画廊站点设置为e-hentai时，则正常重定向到ehgt.org

![1](https://github.com/3003h/FEhViewer/assets/64373235/ada654e6-9727-42b1-a69d-b44652557b8c)
![2](https://github.com/3003h/FEhViewer/assets/64373235/c34a162a-5359-4e49-befd-548e5461f7cb)

**Comment by 3003h** [comment]
已修复
