### ISSUE TITLE
Lag on image loading

### ISSUE THREAD

**Issue by james58899** [3003h/FEhViewer#61]
圖片載入時很卡

https://user-images.githubusercontent.com/5798637/166100390-1521ea22-3b47-4b81-a93d-9feae691ce68.mp4

**Comment by sichuanqianwan** [comment]
请问你解决了吗？> 圖片載入時很卡
> 
> 
> 
> https://user-images.githubusercontent.com/5798637/166100390-1521ea22-3b47-4b81-a93d-9feae691ce68.mp4
> 
> 
> 
>
