### ISSUE TITLE
请问不可以直连吗？

### ISSUE THREAD

**Issue by ghost** [3003h/FEhViewer#80]
请问不可以直连吗？

**Comment by ludenswww** [comment]
> 172.67.0.127

大佬能出个教程之类的吗安装完打开就不会弄来了

**Comment by ludenswww** [comment]
> > 可以直连，但是不同地区网络状况不同，比如我对于e-hentai.org前2个ip（104.20.134.21，104.20.135.21）无法直连 但是172.67.0.127就可以（需要手动指定hosts） 作者只简单指定了几个映射
> > ```dart
> >   static const Map<String, String> internalHosts = {
> >     'e-hentai.org': '104.20.134.21',
> >     // 'api.e-hentai.org': '37.48.89.16',
> >     'api.e-hentai.org': '178.162.147.246',
> >     'forums.e-hentai.org': '172.67.0.127',
> >     'ehgt.org': '178.162.140.212',
> >     'exhentai.org': '178.175.129.252',
> >     'api.exhentai.org': '178.175.128.252',
> >   };
> > ```
> 
> 也许可以多加几个映射，测下ping？

毕竟作者大大都做出来了，用不了实在太遗憾了qwq

**Comment by AjianYo** [comment]
> 可以直连，但是不同地区网络状况不同，比如我对于e-hentai.org前2个ip（104.20.134.21，104.20.135.21）无法直连 但是172.67.0.127就可以（需要手动指定hosts） 作者只简单指定了几个映射
> 
> ```dart
>   static const Map<String, String> internalHosts = {
>     'e-hentai.org': '104.20.134.21',
>     // 'api.e-hentai.org': '37.48.89.16',
>     'api.e-hentai.org': '178.162.147.246',
>     'forums.e-hentai.org': '172.67.0.127',
>     'ehgt.org': '178.162.140.212',
>     'exhentai.org': '178.175.129.252',
>     'api.exhentai.org': '178.175.128.252',
>   };
> ```

iOS怎么实现这个？比如IPA文件应该修改什么地方？
